version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - 5432:5432

  django:
    build:
      context: .
    #volumes:
    #  - .:/app  # Mount the project directory
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: donknabberello
      DJANGO_DB_USER: USER
      DJANGO_DB_PASSWORD: PASSWORD
      DJANGO_WEB_HOST: 192.168.1.190
      DJANGO_WEB_PORT: 8000
    privileged: true  # Grants access to devices and kernel features
    volumes:
      - /dev/gpiomem:/dev/gpiomem  # GPIO access
      - /dev/spidev0.0:/dev/spidev0.0  # SPI access
      - /dev/spidev0.1:/dev/spidev0.1  # SPI access
      - /dev/i2c-1:/dev/i2c-1  # I2C access
      - /dev/serial0:/dev/serial0  # Serial access
      - /dev/ttyUSB0:/dev/ttyUSB0  # USB serial (if required)
    devices:
      - "/dev/gpiomem"
      - "/dev/spidev0.0"
      - "/dev/spidev0.1"
      - "/dev/i2c-1"
      - "/dev/serial0"
      - "/dev/ttyUSB0"
    cap_add:
      - SYS_RAWIO  # Allows raw GPIO access
    security_opt:
      - apparmor:unconfined  # Unrestricted access to hardware

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
